//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artemkv.Darwin.Controller.DarwinServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DarwinServiceReference.IDarwinDataService")]
    public interface IDarwinDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDarwinDataService/GetObject", ReplyAction="http://tempuri.org/IDarwinDataService/GetObjectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.RelationItemDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.RelationDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DiagramDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DiagramEntityDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.EntityDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.AttributeDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.ProjectDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DatabaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DataTypeDTO))]
        Artemkv.Darwin.Common.Responses.GetObjectResponse GetObject(Artemkv.Darwin.Common.Requests.GetObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDarwinDataService/SaveObject", ReplyAction="http://tempuri.org/IDarwinDataService/SaveObjectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.RelationItemDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.RelationDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DiagramDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DiagramEntityDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.EntityDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.AttributeDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.ProjectDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DatabaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DataTypeDTO))]
        Artemkv.Darwin.Common.Responses.SaveObjectResponse SaveObject(Artemkv.Darwin.Common.Requests.SaveObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDarwinDataService/DeleteObject", ReplyAction="http://tempuri.org/IDarwinDataService/DeleteObjectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.RelationItemDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.RelationDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DiagramDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DiagramEntityDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.EntityDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.AttributeDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.ProjectDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DatabaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Artemkv.Darwin.Common.DTO.DataTypeDTO))]
        Artemkv.Darwin.Common.Responses.DeleteObjectResponse DeleteObject(Artemkv.Darwin.Common.Requests.DeleteObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDarwinDataService/GetObjectList", ReplyAction="http://tempuri.org/IDarwinDataService/GetObjectListResponse")]
        Artemkv.Darwin.Common.Responses.GetObjectListResponse GetObjectList(Artemkv.Darwin.Common.Requests.GetObjectListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDarwinDataService/GetTreeNodes", ReplyAction="http://tempuri.org/IDarwinDataService/GetTreeNodesResponse")]
        Artemkv.Darwin.Common.Responses.GetTreeNodesResponse GetTreeNodes(Artemkv.Darwin.Common.Requests.GetTreeNodesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDarwinDataServiceChannel : Artemkv.Darwin.Controller.DarwinServiceReference.IDarwinDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DarwinDataServiceClient : System.ServiceModel.ClientBase<Artemkv.Darwin.Controller.DarwinServiceReference.IDarwinDataService>, Artemkv.Darwin.Controller.DarwinServiceReference.IDarwinDataService {
        
        public DarwinDataServiceClient() {
        }
        
        public DarwinDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DarwinDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarwinDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarwinDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Artemkv.Darwin.Common.Responses.GetObjectResponse GetObject(Artemkv.Darwin.Common.Requests.GetObjectRequest request) {
            return base.Channel.GetObject(request);
        }
        
        public Artemkv.Darwin.Common.Responses.SaveObjectResponse SaveObject(Artemkv.Darwin.Common.Requests.SaveObjectRequest request) {
            return base.Channel.SaveObject(request);
        }
        
        public Artemkv.Darwin.Common.Responses.DeleteObjectResponse DeleteObject(Artemkv.Darwin.Common.Requests.DeleteObjectRequest request) {
            return base.Channel.DeleteObject(request);
        }
        
        public Artemkv.Darwin.Common.Responses.GetObjectListResponse GetObjectList(Artemkv.Darwin.Common.Requests.GetObjectListRequest request) {
            return base.Channel.GetObjectList(request);
        }
        
        public Artemkv.Darwin.Common.Responses.GetTreeNodesResponse GetTreeNodes(Artemkv.Darwin.Common.Requests.GetTreeNodesRequest request) {
            return base.Channel.GetTreeNodes(request);
        }
    }
}
